// THIS FILE WAS AUTOGENERATED - ANY EDITS TO THIS WILL BE LOST WHEN IT IS REGENERATED

package model

import "github.com/google/uuid"

type ColorReferenceTable struct {
	Value string `db:"value" json:"value"`
}

type Person struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Height    float64   `db:"height" json:"height"`
	Mass      float64   `db:"mass" json:"mass"`
	HairColor Color     `db:"hair_color" json:"hair_color"`
	SkinColor Color     `db:"skin_color" json:"skin_color"`
	EyeColor  Color     `db:"eye_color" json:"eye_color"`
	BirthYear int       `db:"birth_year" json:"birth_year"`
	Gender    Gender    `db:"gender" json:"gender"`
	HomeWorld string    `db:"home_world" json:"home_world"`
}
