package templates

const ModelTemplate = `
// THIS FILE WAS AUTOGENERATED - ANY EDITS TO THIS WILL BE LOST WHEN IT IS REGENERATED

{{ $schema := .Schema }}
package {{ .Package }}

import "github.com/lumina-tech/gooq/pkg/gooq"

{{ range $_, $table := .Tables -}}
type {{ $table.ModelType }} struct {
  {{ range $_, $f := $table.Fields -}}
  {{ snakeToCamelID $f.Name }} {{ $f.Name }} ` + "`db:\"{{ $f.Name }}\" json:\"{{ $f.Name }}\"`" + `
  {{ end }}
}
{{ end }}
`
